# static site cache
services:
  - type: web
    name: cdn-cache
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 16.8.0
      - key: GITHUB_TOKEN
        sync: false
      
# server
  - type: web
    name: node-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 16.8.0
      - key: GITHUB_TOKEN
        sync: false
