# static site cache
services:
  - type: web
    name: cdn-cache
    env: static
    buildCommand: yarn; yarn build; yarn next export
    staticPublishPath: out
    autoDeploy: false
    #routes:
    #  - type: rewrite
    #    source: /*
    #    destination: https://node-server-h4yl.onrender.com/*
    envVars:
      - key: NODE_VERSION
        value: 16.8.0
      - key: GITHUB_TOKEN
        sync: false
# server
  - type: web
    name: node-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: 16.8.0
      - key: GITHUB_TOKEN
        sync: false
